package vaultservice

import (
	"github.com/gin-gonic/gin"
	"net/http"
)

func NewClientCertResultMessage(ctx *gin.Context, clientCert, clientKey []byte) {
	er := HTTPCertResult{
		Cert:         clientCert,
		EncryptedKey: clientKey,
	}
	ctx.JSON(http.StatusOK, er)
}

type HTTPCertResult struct {
	Cert []byte `json:"cert" example:"-----BEGIN CERTIFICATE-----
MIICzjCCAlSgAwIBAgIGAY4ImKCzMAoGCCqGSM49BAMDMIGdMQswCQYDVQQGEwJD
SDETMBEGA1UECBMKQmFzZWwgQ2l0eTEOMAwGA1UEBxMFQmFzZWwxIDAeBgNVBAkM
F1NjaMO2bmJlaW5zdHJhc3NlIDE4LTIwMQ0wCwYDVQQREwQ0MDU2MSEwHwYDVQQK
ExhVbml2ZXJzaXR5IExpYnJhcnkgQmFzZWwxFTATBgNVBAMTDE1pbmlWYXVsdCBD
QTAeFw0yNDAzMDQwODMzMjRaFw0zNDAzMDIwODMzMjRaMIGdMQswCQYDVQQGEwJD
SDETMBEGA1UECBMKQmFzZWwgQ2l0eTEOMAwGA1UEBxMFQmFzZWwxIDAeBgNVBAkM
F1NjaMO2bmJlaW5zdHJhc3NlIDE4LTIwMQ0wCwYDVQQREwQ0MDU2MSEwHwYDVQQK
ExhVbml2ZXJzaXR5IExpYnJhcnkgQmFzZWwxFTATBgNVBAMTDE1pbmlWYXVsdCBD
QTB2MBAGByqGSM49AgEGBSuBBAAiA2IABNqguitxVjzwfhGwfxuYb6ZU/nQYAUMK
Ik7iAOaHLCUObbvPq5e9YNB8bOVz0SPD9eSaGylGpHLamnvh41a8SyQhvCB76IaE
kiP8KW2rZk2R15ofdhOEscHJjUlxtR0HIKNhMF8wDgYDVR0PAQH/BAQDAgKEMB0G
A1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0G
A1UdDgQWBBSoWy7F4ezDX2MBVLtPncSDeVaH+DAKBggqhkjOPQQDAwNoADBlAjAZ
Ievr3SDRdSF3RjC5TVUpmGUBU2pRQNCFulXfs/4Dp1Yf9f0cv6jL6t2AI/XxmTgC
MQCooq/KjFB/+1TGoOIdZDBtkfKkbD3EIcnV3DvXMQ+4EOoorfGCxOR5Qx9lhPm1
IAM=
-----END CERTIFICATE-----"`
	EncryptedKey []byte `json:"key" example:"-----BEGIN ENCRYPTED PRIVATE KEY-----
MIIBJTBgBgkqhkiG9w0BBQ0wUzAyBgkqhkiG9w0BBQwwJQQQgqKDgsoFu1GCaNfb
dgNKrQIDCSfAMAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUDBAEqBBBSKHkce2NWqrvQ
H2+PWmsMBIHAWJnJ8mKC1sbO6aKrJtpnq5eYWWsu4wnOek2MsXCoeHmUGmYXFrcn
+ojD7BmP2H0fSfr/3UXCx7c91cup4Vmuz7KK+3WGi993wbsQBQUP8X6FXJ5f54CT
8zX6zrDucLnOvuBR6ydJ6qL5+ZChK+X6X9IVDYk266KYXhjWw1QdRu2Y0z49ssZO
mOLFNP99NQqY9z5+JF/Q6rMnXbf25U2nbQ+lm0PJ4dWdeiNRLUvxOpJ7xyQzz9Iq
k4YbwhEVHvEU
-----END ENCRYPTED PRIVATE KEY-----"`
}
